### ISSUE TITLE
Feature Request: Destination user, group, permissions

### ISSUE THREAD

**Issue by linuxdan** [KimNorgaard/KimNorgaard-httpfile#16]
I am going to try just using a file resource to set the user, group and permissions, but it would be nice to roll it into the ruby code.

I may try it myself.

**Comment by KimNorgaard** [comment]
See https://github.com/KimNorgaard/KimNorgaard-httpfile/issues/7#issuecomment-75857109

Feel free to provide a PR with an optional method for settings ownership and permissions but if you do, please make sure it works cross-platform :)
