### ISSUE TITLE
Check checksum after successful download

### ISSUE THREAD

**Issue by KimNorgaard** [KimNorgaard/KimNorgaard-httpfile#4]
An option should be added to compare the checksum of the downloaded file to the one it is supposed to have.

An error should be raised if they differ.

**Comment by elatt** [comment]
+1

Not checking the checksum after download could also cause an infinite update loop if the user is using expected_checksum and the upstream updates the file without you knowing. It can also happen if the upstream calculates the wrong MD5 sum in the HTTP headers or has wrong sidecar files.
