### ISSUE TITLE
Support 'mode'

### ISSUE THREAD

**Issue by abh** [KimNorgaard/KimNorgaard-httpfile#7]
It'd be nice if httpfile supported the 'mode' parameter similar to the 'file' provider. Other users might have a similar need for other parameters from that provider.

**Comment by elatt** [comment]
File modes/acls are a mess (especially under windows) and the advantage of this module is that it works cross platforms. I would advocate in rejecting this request and requiring users to set the ACLs via a different resource: either a file resource with no source or content and requires httpfile or a acl resource on windows.

**Comment by KimNorgaard** [comment]
I'm with elatt on this.
